Add queue service example with producer and consumer.
ivcap-works/ivcap-python-service-example pull request #3
Opened 2024-05-09 01:41 UTC by bclews

This pull request adds a new example demonstrating the use of the IVCAP Queue service. It includes a producer service that simulates publishing temperature data from buoys to a queue, and a consumer service that retrieves and logs the data from the queue. The example showcases a practical application of using queues in a distributed system for processing environmental data in the scientific domain.

2024-05-09 01:43 UTC, bclews commented on queue/consumer/requirements.txt
> +git+https://github.com/ivcap-works/ivcap-service-sdk-python@queue_svc#egg=ivcap_sdk_service
This is currently pinned to the `queue_svc` branch of the `ivcap-service-sdk-python`, which is ready for review. Once that branch gets merged into develop/main I will update these requirements files.

2024-05-20 05:06 UTC, maxott requested changes

2024-05-20 05:06 UTC, maxott commented on queue/producer/service.yaml
> +env IVCAP_SERVICE_ID=ivcap:service:e5fb1c5f-79ed-55bc-ab86-89aa44c8055c:queue-producer-service \
Why is this file here?

2024-05-20 05:12 UTC, bclews commented on queue/producer/service.yaml
> +env IVCAP_SERVICE_ID=ivcap:service:e5fb1c5f-79ed-55bc-ab86-89aa44c8055c:queue-producer-service \
My carelessness! I will remove.

2024-05-20 05:18 UTC, bclews commented on queue/consumer/requirements.txt
> +git+https://github.com/ivcap-works/ivcap-service-sdk-python@queue_svc#egg=ivcap_sdk_service
Updated to point to `develop` now instead of `queue_svc`

2024-05-20 05:19 UTC, bclews commented on queue/producer/service.yaml
> +env IVCAP_SERVICE_ID=ivcap:service:e5fb1c5f-79ed-55bc-ab86-89aa44c8055c:queue-producer-service \
Updated.

2024-05-20 05:37 UTC, bclews commented
Thanks for the review @maxott. 

The following commits removes the unnecessary queue producer service configuration and updates the requirements files to point to `ivcap-service-sdk-python@develop`:
- 6a7b93331fbdfb977c7ee780dec2415ada3a4b65
- bceb97eab90c4c61bf73c2c2362faf06d515cf5f

2024-07-31 22:43 UTC, merged